install.packages("magrittr")
install.packages ("tm")
install.packages ("SnowballC")
install.packages ("wordcloud")
install.packages ("ggplot2")
install.packages ("dplyr")
install.packages ("readr")
install.packages ("cluster")
install.packages ("lsa")
install.packages ("RColorBrewer")
scatterplot3d
library(NLP)
library(tm)
library(RColorBrewer)
library(SnowballC)
library(wordcloud)
library(ggplot2)
library(dplyr)
library(readr)
library(cluster)
library(lsa)
library(bitops)
library(RCurl)


install.packages("magrittr")
library(magrittr)

install.packages("sos")
install.packages("brew")
library(bew)
library(sos)
